export const Users = [{
        id: 1,
        avatar: "profile/001.jpg",
        username: "Safak Kocaoglu",
    },
    {
        id: 2,
        avatar: "profile/002.jpg",
        username: "Janell Shrum",
    },
    {
        id: 3,
        avatar: "profile/003.jpg",
        username: "Alex Durden",
    },
    {
        id: 4,
        avatar: "profile/004.jpg",
        username: "Dora Hawks",
    },
    {
        id: 5,
        avatar: "profile/005.jpg",
        username: "Thomas Holden",
    },
    {
        id: 6,
        avatar: "profile/006.jpg",
        username: "Shirley Beauchamp",
    },
    {
        id: 7,
        avatar: "profile/007.jpg",
        username: "Travis Bennett",
    },
    {
        id: 8,
        avatar: "profile/008.jpg",
        username: "Kristen Thomas",
    },
    {
        id: 9,
        avatar: "profile/009.jpg",
        username: "Gary Duty",
    },
    {
        id: 10,
        avatar: "profile/010.jpg",
        username: "Safak Kocaoglu",
    },
];

export const Posts = [{
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "post/1.webp",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "post/2.webp",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "post/3.webp",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "post/4.webp",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "post/5.webp",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "post/6.webp",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "post/7.webp",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "post/8.webp",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "post/9.webp",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "post/10.jpeg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];